remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

header_pages:
  - index.md
  - about.md
  - PSC.html

minima:
  skin: auto

  minima:
  social_links:
    - { platform: instagram, user_url: "https://instagram.com/matt_wyz" }
    - { platform: twitter, user_url: "https://twitter.com/matt_wyz" }
    - { platform: youtube, user_url: "https://youtube.com/@matt_wyz" }
